 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bookrakes", type: :request do
  
  # Bookrake. As you add validations to Bookrake, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bookrake.create! valid_attributes
      get bookrakes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bookrake = Bookrake.create! valid_attributes
      get bookrake_url(bookrake)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bookrake_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bookrake = Bookrake.create! valid_attributes
      get edit_bookrake_url(bookrake)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bookrake" do
        expect {
          post bookrakes_url, params: { bookrake: valid_attributes }
        }.to change(Bookrake, :count).by(1)
      end

      it "redirects to the created bookrake" do
        post bookrakes_url, params: { bookrake: valid_attributes }
        expect(response).to redirect_to(bookrake_url(Bookrake.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bookrake" do
        expect {
          post bookrakes_url, params: { bookrake: invalid_attributes }
        }.to change(Bookrake, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bookrakes_url, params: { bookrake: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bookrake" do
        bookrake = Bookrake.create! valid_attributes
        patch bookrake_url(bookrake), params: { bookrake: new_attributes }
        bookrake.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bookrake" do
        bookrake = Bookrake.create! valid_attributes
        patch bookrake_url(bookrake), params: { bookrake: new_attributes }
        bookrake.reload
        expect(response).to redirect_to(bookrake_url(bookrake))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bookrake = Bookrake.create! valid_attributes
        patch bookrake_url(bookrake), params: { bookrake: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bookrake" do
      bookrake = Bookrake.create! valid_attributes
      expect {
        delete bookrake_url(bookrake)
      }.to change(Bookrake, :count).by(-1)
    end

    it "redirects to the bookrakes list" do
      bookrake = Bookrake.create! valid_attributes
      delete bookrake_url(bookrake)
      expect(response).to redirect_to(bookrakes_url)
    end
  end
end
